Update Website to Apoapsis 2020
ApoapsisHGV/ApoapsisHGV.github.io pull request #30
Opened 2020-10-20 16:45 UTC by ccode20

All the information like blogposts,team members, ... has been added

2020-10-20 20:33 UTC, fxedel requested changes
Sehr schön gemacht! Ich hab nur noch ein paar Kleinigkeiten und Tippfehler angemerkt :wink:

2020-10-20 20:33 UTC, fxedel commented on de/CanSat2019/about2019.md
> +title: Über uns und das Projekt
```suggestion
title: CanSat 2019: Über uns und das Projekt
```

Dann ist wenn man auf der Seite ist vielleicht klarer, dass es um den vorherigen Wettbewerb ging

2020-10-20 20:33 UTC, fxedel commented on _config.yml
> +name: Apoapsis 2020
```suggestion
name: Apoapsis 2020/21
```

Auf der CanSat-Homepage steht ja 2020/21, vielleicht sollten wir das dann auch so machen

2020-10-20 20:33 UTC, fxedel commented on de/CanSat2019/sponsoren2019.md
> +---
Brauchts die Seite noch? Ist ja in cansat2019.md auch schon alles mit drin

2020-10-20 20:33 UTC, fxedel commented on de/CanSat2019/cansat2019.md
> +    <img src="{{ site.baseurl }}/images/2020-team-members/teresa.jpg" />
```suggestion
    <img src="{{ site.baseurl }}/images/2019-team-members/teresa.jpg" />
```

Oder `2019-team-members/Teresa.jpg` – bei den Bildern muss auf Groß-/Kleinschreibung geachtet werden

2020-10-20 20:33 UTC, fxedel commented on de/index.md
> +Die Software hingegen ist Manuel und Daniels Spezialgebiet.
```suggestion
Die Software hingegen ist Manuels und Daniels Spezialgebiet. 
```

2020-10-20 20:33 UTC, fxedel commented on de/index.md
> +Chiara hält die Webseite in Stand und verwaltet zusammen mit Teresa die Social-Media- Kanäle.
```suggestion
Chiara hält die Webseite in Stand und verwaltet zusammen mit Teresa die Social-Media-Kanäle. 
```

2020-10-20 20:33 UTC, fxedel commented on de/index.md
> +Anna ist für die Entwicklung und das Testen unseres Bergungssystems, also unseren Fallschirm, zuständig.
```suggestion
Anna ist für die Entwicklung und das Testen unseres Bergungssystems, also unseres Fallschirms, zuständig. 
```

2020-10-20 20:33 UTC, fxedel commented on de/about.md
> +Unser CanSat kann zum einen den Luftdruck und die Temperatur während des Fluges messen, zum anderen erkennt er Objekte von oben. Um dies zu bewerkstelligen verwenden wir eine oder mehrere Kameras, di
```suggestion
Unser CanSat kann zum einen den Luftdruck und die Temperatur während des Fluges messen, zum anderen erkennt er Objekte von oben. Um dies zu bewerkstelligen, verwenden wir eine oder mehrere Kameras, die Bilder von der Erdoberfläche und der darauf verteilten Objekte aufnehmen. Danach wollen wir diese Bilder mithilfe von Microsoft-APIs analysieren und eine Karte erstellen, auf der die verschiedenen Objekte und deren Lage zu sehen sind.
```

2020-10-20 20:33 UTC, fxedel commented on de/team.md
> +    <img src="{{ site.baseurl }}/images/2020-team-members/teresa.jpg" />
```suggestion
    <img src="{{ site.baseurl }}/images/2020-team-members/Teresa.jpg" />
```

2020-10-20 20:33 UTC, fxedel commented on de/team.md
> +    <img src="{{ site.baseurl }}/images/2020-team-members/jakob.jpg" />
```suggestion
    <img src="{{ site.baseurl }}/images/2020-team-members/Jakob.jpg" />
```

2020-10-20 20:33 UTC, fxedel commented on de/team.md
> +    <img src="{{ site.baseurl }}/images/2020-team-members/manuel.jpg" />
```suggestion
    <img src="{{ site.baseurl }}/images/2020-team-members/Manuel.jpg" />
```

2020-10-20 20:33 UTC, fxedel commented on de/team.md
> +    <img src="{{ site.baseurl }}/images/2020-team-members/daniel.jpg" />
```suggestion
    <img src="{{ site.baseurl }}/images/2020-team-members/Daniel.jpg" />
```

2020-10-20 20:33 UTC, fxedel commented on de/team.md
> +  <span>„Ich bin <strong>Anna Eckstein</strong> und bringe mich bei der Konstruktion der Hardware und Elektronik ein. Außerdem helfe ich Jakob beim 3D-modellieren des CanSats. Ich gehe in die 9 Klass
```suggestion
  <span>„Ich bin <strong>Anna Eckstein</strong> und bringe mich bei der Konstruktion der Hardware und Elektronik ein. Außerdem helfe ich Jakob beim 3D-Modellieren des CanSats. Ich gehe in die 9. Klasse, weshalb ich zum Nachwuchs unseres Teams gehöre.“</span>
```

2020-10-20 20:33 UTC, fxedel commented on en/CanSat2019/cansat2019.md
> +    <img src="{{ site.baseurl }}/images/2020-team-members/teresa.jpg" />
```suggestion
    <img src="{{ site.baseurl }}/images/2019-team-members/teresa.jpg" />
```

2020-10-20 20:33 UTC, fxedel commented on en/CanSat2019/competitiondays2019.md
> +permalink: en/cansat2019/wettbewerbstage2019/
```suggestion
permalink: en/cansat2019/competitiondays2019/
```

2020-10-20 20:33 UTC, fxedel commented on en/index.md
> +The software, on the other hand, is Manuel and Daniel's specialty.
```suggestion
The software, on the other hand, is Manuel's and Daniel's specialty. 
```

2020-10-20 20:33 UTC, fxedel commented on en/team.md
> +    <img src="{{ site.baseurl }}/images/2020-team-members/teresa.jpg" />
```suggestion
    <img src="{{ site.baseurl }}/images/2020-team-members/Teresa.jpg" />
```

2020-10-20 20:33 UTC, fxedel commented on en/team.md
> +    <img src="{{ site.baseurl }}/images/2020-team-members/jakob.jpg" />
```suggestion
    <img src="{{ site.baseurl }}/images/2020-team-members/Jakob.jpg" />
```

2020-10-20 20:33 UTC, fxedel commented on en/team.md
> +    <img src="{{ site.baseurl }}/images/2020-team-members/manuel.jpg" />
```suggestion
    <img src="{{ site.baseurl }}/images/2020-team-members/Manuel.jpg" />
```

2020-10-20 20:33 UTC, fxedel commented on en/team.md
> +    <img src="{{ site.baseurl }}/images/2020-team-members/daniel.jpg" />
```suggestion
    <img src="{{ site.baseurl }}/images/2020-team-members/Daniel.jpg" />
```

2020-10-20 20:33 UTC, fxedel commented on en/team.md
> +  <span>„My name is <strong> Daniel Hechtfischer </strong>. I help Manuel programming and controlling our CanSat. I also became aware of the project through a presentation at the <a href="http://www.
```suggestion
  <span>„My name is <strong>Daniel Hechtfischer </strong>. I help Manuel programming and controlling our CanSat. I also became aware of the project through a presentation at the <a href="http://www.humboldt-gym.de/node/135" target="_blank" >Humboldt Academy for Science and Engineering (HASE) </a> at our school.“</span>
```

2020-10-20 20:33 UTC, fxedel commented on en/CanSat2019/about2019.md
> +title: About us and the project
```suggestion
title: CanSat 2019: About us and the project
```

2020-10-21 15:57 UTC, ccode20 reviewed
Korrigiert

2020-10-21 15:57 UTC, ccode20 commented on de/CanSat2019/sponsoren2019.md
> +---
Hatte eigentlich vor den Sponsorenteil etwas zu verändern. Hat sich aber aufrund der Vorgaben der Sponsoren erledigt.

2020-10-21 15:57 UTC, ccode20 commented on de/CanSat2019/cansat2019.md
> +    <img src="{{ site.baseurl }}/images/2020-team-members/teresa.jpg" />
Teresa wollte, dass ich ihr altes Bild ersetze

2020-10-21 15:57 UTC, ccode20 commented on de/team.md
> +    <img src="{{ site.baseurl }}/images/2020-team-members/teresa.jpg" />
Bei mir sind die Bildnamen alle klein geschrieben, hatte sie eigentlich schon vor einer Weile geändert. Wurde aber anscheinend beim Pushen nicht mitgenommen.

2020-10-21 15:58 UTC, ccode20 commented
Vielen Dank für die Rückmeldungen

2020-10-21 15:58 UTC, merged